### ISSUE TITLE
exporter-merger absence of k8s example

### ISSUE THREAD

**Issue by paskal** [rebuy-de/exporter-merger#4]
Hello, team!

Thank you for your work. https://github.com/rebuy-de/exporter-merger repo doesn't have issues, so I'd have to create one here: could you please include k8s usage example into exporter-merger and teach it to use ENV variables and not only CLI arguments?
Also it would be really cool of you to publish docker image at quay.io, now it seems to be private.

Thanks!

**Comment by bjoernhaeuser** [comment]
Hi Paskal,

how could that env configuration look like?

**Comment by paskal** [comment]
Port as an integer, and [something like this](https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable) for list of URLs (most easily achievable by entrypoint shell script). Alternative is to alter program to get same information from CLI with, let's say, comma delimeter - it's much easier and will work good enough.
I want to be able to have something like that in k8s configuration:
```yaml
          env:
          - name: MERGER_PORT
            value: 8080
          - name: MERGER_URLS_LIST
            value: http://localhost:8888/metrics,http://localhost:9090/prometheus/metrics
```
